### ISSUE TITLE
change method to sync?

### ISSUE THREAD

**Issue by severo** [hyparam/hightable#6]
The implemention is synchronous, should we change to `rows(start: number, end: number): Row[] {`?

https://github.com/hyparam/hightable/blob/e221f3777b10b9245738e1ba404316a5b93c386c/src/dataframe.ts#L158

**Comment by platypii** [comment]
No it needs to return a `Promise<Row[]>` or else it won't match the return type of `DataFrame`.

We could remove the `async` and instead `return Promise.resolve(data.slice(start, end))` but doesn't seem to make a huge difference.

I assume you're looking at this because of linting. Removing unnecessary async's are good in general but in this case the linter is wrong because the async may not have an await but it IS changing the return type of the function. I'd probably just `eslint-disable` this line.

**Comment by severo** [comment]
exactly. Doing this
